[package]
name = "burn-import-model-checks-yolo11x"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[features]
default = ["ndarray"]
ndarray = []
tch = []

[dependencies]
burn = { path = "../../../../crates/burn", features = ["ndarray", "tch"] }

[build-dependencies]
burn-import = { path = "../../../burn-import" }
